In [1]:
import numpy as np
from src.neural_network import NeuralNetwork


In [2]:
data = np.loadtxt('src\MNIST-5-6-Subset\MNIST-5-6-Subset.txt')
labels = np.loadtxt('src\MNIST-5-6-Subset\MNIST-5-6-Subset-Labels.txt')

In [3]:
model =NeuralNetwork()
model.add_layer(2, Input=True)
model.add_layer(3)
model.add_layer(2)
model.show_structur()


[array([0., 0.]), array([0., 0., 0.]), array([0., 0.])]


In [4]:
model.Forward([1,2])

[0.3657623  0.49362472 0.14061298]
[0.64246059 0.35753941]


In [5]:
model.layers

[[1, 2],
 array([0.3657623 , 0.49362472, 0.14061298]),
 array([0.64246059, 0.35753941])]

In [6]:
a = [[1,2],[3,4]]
b = [10, 10]
np.dot(a,b)

array([30, 70])

In [7]:
def fun(x, a=1):
    return 2*x*a

fun2 =np.vectorize(fun)

In [8]:
fun([1,2])
fun2([1,2],3)


array([ 6, 12])