In [1]:
import numpy as np
from src.neural_network import NeuralNetwork

In [2]:
data = np.loadtxt('src\MNIST-5-6-Subset\MNIST-5-6-Subset.txt')
labels = np.loadtxt('src\MNIST-5-6-Subset\MNIST-5-6-Subset-Labels.txt')

In [3]:
model =NeuralNetwork()
model.add_layer(2, Input=True)
model.add_layer(3)
model.add_layer(2)
model.show_structur()


[array([0., 0.]), array([0., 0., 0.]), array([0., 0.])]


In [4]:
model.layers

[array([0., 0.]), array([0., 0., 0.]), array([0., 0.])]

In [5]:
a=model.layers[1-1]
b=model.Weights[1]
c =model.Biases[1]
a,b,c

(array([0., 0.]),
 array([[0.95034145, 0.23925088],
        [0.97346475, 0.24711479],
        [0.21473674, 0.02493179]]),
 array([0., 0.]))

In [6]:
model.Forward([1,2])

[2.27355376 2.33894771 0.88986018]
[4.62862119 1.14412413]


In [7]:
model.layers

[[1, 2],
 array([2.27355376, 2.33894771, 0.88986018]),
 array([4.62862119, 1.14412413])]

In [8]:
a = [[1,2],[3,4]]
b = [10, 10]
np.dot(a,b)

array([30, 70])